name: Build

on:
  pull_request:
    paths-ignore:
      - '**.md'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install

      - name: Bump project's version
        id: version
        shell: bash
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          yarn release
          PACKAGE_VERSION=$(node -p -e "require('./package.json').version")
          echo ::set-output name=TAG::${PACKAGE_VERSION}

      - name: Generate token for GitHub App
        id: generate-token
        uses: getsentry/action-github-app-token@v1
        with:
          app_id: ${{ secrets.GH_APP_PUSH_TO_PROTECTED_BRANCH_ID }}
          private_key: ${{ secrets.GH_APP_PUSH_TO_PROTECTED_BRANCH_PRIVATE_KEY }}

      - name: Commit and push it to a protected branch
        uses: Amraneze/push-to-protected-branch@v1.5.0
        with:
          create_tag: true
          repository: ${{ github.repository	}}
          branch_name: 'main'
          tag_version: ${{ steps.version.outputs.TAG }}
          github_token: ${{ steps.generate-token.outputs.token }}
          commit_message: 'ci: build version v${{ steps.version.outputs.TAG }} - [actions skip]'
          files_to_commit: 'package.json,CHANGELOG.md,README.md'